name: Run Django Tests and Merge

on:
  push:
    branches:
      - development

# concurrency: 
#     group: testing
#     cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      db:
        image: postgres
    env:
        POSTGRES_DB: tm_db
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS dependencies
        run: |
          apt-get update \
          && apt-get -y install libpq-dev gcc

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Django tests
        run: |
          python manage.py test

  merge:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash "$GITHUB_REF"
